### ISSUE TITLE
How to remove column from ModelFieldGroup dynamically?

### ISSUE THREAD

**Issue by zerk174** [Qualtagh/JBroTable#2]
How to remove column from ModelFieldGroup dynamically? :)

**Comment by Qualtagh** [comment]
I have added a method `addColumn` (JBroTableModel class) with the signature you suggested and will add a method `removeColumn` as well. Though I can't tell a deadline for this. I have almost no time these days unfortunately.

**Comment by Qualtagh** [comment]
I hope it's better late than never. Added a method `removeColumn` (JBroTableModel class).

Also, note that these methods change the model. If you want to change the view (in model-view-controller terms), consider using `reorderFields( String fieldIds[] )` method of JBroTable. You can pass an array of model fields with skipped values (they will be hidden) and different order (they will be swapped).

Model changing methods rebuild the whole model array. View changing methods just mark fields as hidden/visible. So, it's faster to change the view (if it suits your needs).

**Comment by zerk174** [comment]
Hooray! I'm tested removeColumn, it works as it should. Thanks, great work, you made really usefull component, all other variants looks ugly even javafx TableView sometimes looks ugly after user move columns!
