### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by liponcio** [Qualtagh/JBroTable#4]
This is a great job, thanks a lot for this.
Is there any chance you deploy it in a maven repo?

Thanks

**Comment by Qualtagh** [comment]
Done. I hope it's better late than never.

Can be added like this:

```xml
<dependency>
  <groupId>io.github.qualtagh.swing.table</groupId>
  <artifactId>JBroTable</artifactId>
  <version>2.0</version>
</dependency>
```

I'll update documentation later.

Also, I had to change package name (`org.quinto` -> `io.github.qualtagh`). I'm sorry for inconvenience, you'll have to change accordingly in your code.

**Comment by Qualtagh** [comment]
Updated docs
