### ISSUE TITLE
Make table cannot be editable?

### ISSUE THREAD

**Issue by SpQuyt** [Qualtagh/JBroTable#5]
Hello,

I wanna ask you if you can show me the way to make this table cannot be editable: like make that table cannot be resized or dragged.

**Comment by Qualtagh** [comment]
Hi,

prohibit resizing:
```java
table.getTableHeader().setResizingAllowed( false );
```

prohibit dragging:
```java
table.getTableHeader().setReorderingAllowed( false );
```

**Comment by SpQuyt** [comment]
Thank you so much <3
